// nodegraph.js (renderer)
const NodeGraph = (function(){
  const NS = "http://www.w3.org/2000/svg";
  function createSVG(w=900,h=420){ const svg = document.createElementNS(NS,'svg'); svg.setAttribute('viewBox',`0 0 ${w} ${h}`); svg.setAttribute('preserveAspectRatio','xMidYMid meet'); svg.style.width='100%'; svg.style.height='100%'; return svg; }
  function draw(graph, svgEl, opts){ while(svgEl.firstChild) svgEl.removeChild(svgEl.firstChild); const gEdges=document.createElementNS(NS,'g'); graph.edges.forEach(e=>{ const a=graph.nodes[e.from], b=graph.nodes[e.to]; const line=document.createElementNS(NS,'line'); line.setAttribute('x1',a.x); line.setAttribute('y1',a.y); line.setAttribute('x2',b.x); line.setAttribute('y2',b.y); line.setAttribute('stroke','#2aa6ff'); line.setAttribute('stroke-width',2); gEdges.appendChild(line); }); svgEl.appendChild(gEdges); const gNodes=document.createElementNS(NS,'g'); Object.values(graph.nodes).forEach(n=>{ const group=document.createElementNS(NS,'g'); const rect=document.createElementNS(NS,'rect'); rect.setAttribute('x', n.x-70); rect.setAttribute('y', n.y-20); rect.setAttribute('width',140); rect.setAttribute('height',40); rect.setAttribute('rx',8); rect.setAttribute('fill', n.type==='decision' ? '#1b3a44' : '#0f4f66'); rect.setAttribute('stroke','#7ec8ff'); rect.setAttribute('stroke-width',1); group.appendChild(rect); const text=document.createElementNS(NS,'text'); text.setAttribute('x', n.x); text.setAttribute('y', n.y+6); text.setAttribute('text-anchor','middle'); text.setAttribute('fill','#e6f7ff'); text.setAttribute('font-size','12'); text.textContent = n.title; group.appendChild(text); rect.style.cursor='pointer'; rect.addEventListener('click', ()=>{ if(opts && opts.onNodeClick) opts.onNodeClick(n); }); text.addEventListener('click', ()=>{ if(opts && opts.onNodeClick) opts.onNodeClick(n); }); gNodes.appendChild(group); }); svgEl.appendChild(gNodes); }
  function GraphUI(opts){ this.containerId = opts && opts.containerId ? opts.containerId : null; this.onNodeClick = opts && opts.onNodeClick ? opts.onNodeClick : null; this.svg = createSVG(opts.width||900, opts.height||420); if(this.containerId){ const c = document.getElementById(this.containerId); if(!c) throw new Error("Container not found: "+this.containerId); c.innerHTML=''; c.appendChild(this.svg); } }
  GraphUI.prototype.loadAndRender = function(graph){ this.graph = graph; draw(graph, this.svg, { onNodeClick: this.onNodeClick }); };
  return GraphUI;
})();
export default NodeGraph;
